name: Git Fastlane

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
    - uses: actions/checkout@v3
    - run: echo "The ${{ github.repository }} repository has been cloned."
    - run: echo "Setting up JDK" 
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - run: echo "The workflow is now ready to test your code."
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - run: echo "Building Debug APK."  
    - name: Run tests
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew build
    - run: echo "Build status report=${{ job.status }}."
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
    - name: Deploy to Google Play (for Android)
      run: bundle lock --add-platform x86_64-linux
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - uses: maierj/fastlane-action@v3.0.0
      with:
        lane: 'test'
